---
- name: Listen for events from AlertManager
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
      filters:
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: condicao DEBUG
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
